# Generated by Django 3.0.5 on 2021-04-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
    ]
